# dein default
[[plugins]]
repo = 'Shougo/neocomplete'
if = "has('lua')"
hook_add = """
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#auto_completion_start_length = 4
"""
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = 'Shougo/vimshell'

# my settings
[[plugins]]
repo = 'kannokanno/previm'
hook_add = """
  augroup PrevimSettings
    autocmd!
    autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
  augroup END
"""
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'let NERDTreeShowHidden = 1'
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = """
  set laststatus=2
  let g:lightline = {
          \ 'mode_map': {'c': 'NORMAL'},
          \ 'active': {
          \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ],
          \   'right': [ ['datetime'] , [ 'percent', 'lineinfo' ], [ 'fileformat', 'fileencoding', 'filetype' ] ]
          \ },
          \ 'component_function': {
          \   'modified': 'MyModified',
          \   'readonly': 'MyReadonly',
          \   'fugitive': 'MyFugitive',
          \   'filename': 'MyFilename',
          \   'fileformat': 'MyFileformat',
          \   'filetype': 'MyFiletype',
          \   'fileencoding': 'MyFileencoding',
          \   'mode': 'MyMode',
          \   'datetime': 'MyDatetime'
          \ }
          \ }

  function! MyModified()
    return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
  endfunction

  function! MyReadonly()
    return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
  endfunction

  function! MyFilename()
    return ('' != MyReadonly() ? MyReadonly() . ' ' : '') .
          \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
          \  &ft == 'unite' ? unite#get_status_string() :
          \  &ft == 'vimshell' ? vimshell#get_status_string() :
          \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
          \ ('' != MyModified() ? ' ' . MyModified() : '')
  endfunction

  function! MyFugitive()
    try
      if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
        return fugitive#head()
      endif
    catch
    endtry
    return ''
  endfunction

  function! MyFileformat()
    return winwidth(0) > 70 ? &fileformat : ''
  endfunction

  function! MyFiletype()
    return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype : 'no ft') : ''
  endfunction

  function! MyFileencoding()
    return winwidth(0) > 70 ? (strlen(&fenc) ? &fenc : &enc) : ''
  endfunction

  function! MyMode()
    return winwidth(0) > 60 ? lightline#mode() : ''
  endfunction

  function! MyDatetime()
    return winwidth(0) > 60 ? strftime("%F %T") : ''
  endfunction
"""
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = """
  nmap <C-_> <Plug>(caw:hatpos:toggle)
  vmap <C-_> <Plug>(caw:hatpos:toggle)
"""
[[plugins]]
repo = 'tpope/vim-obsession'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = """
  let g:quickrun_config={
  \   '_': {
  \     'split': ':botright',
  \     'into': 1
  \   }
  \}
"""
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = "let g:table_mode_corner='|'"

## color
[[plugins]]
repo = 'chriskempson/base16-vim'
[[plugins]]
repo = 'sickill/vim-monokai'
[[plugins]]
repo = 'flazz/vim-colorschemes'

## syntax
[[plugins]]
repo = 'evidens/vim-twig'
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'kchmck/vim-coffee-script'
[[plugins]]
repo = 'elzr/vim-json'
[[plugins]]
repo = 'slim-template/vim-slim'

## help
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
